# Generated by Django 2.0.9 on 2018-11-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
